trigger:
- main

variables:
  azureSubscription: 'subscription-id'
  webAppName: 'web-app-name'
  vmImageName: 'ubuntu-latest'
  environmentName: 'environment-name'
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: Build stage
  variables:
    phpVersion: '7.4'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        # Your build steps here
        echo "Building PHP app..."
      displayName: 'Build PHP'
